# Pandasda join ve grouping

In [ ]:
import pandas as pd

In [ ]:
cedvel1= pd.DataFrame()
cedvel1["student_id"]=[100,101,103,104,105]
cedvel1["age"]=[20,25,22,26,22]

In [ ]:
cedvel1

   student_id  age
0         100   20
1         101   25
2         103   22
3         104   26
4         105   22

In [ ]:
cedvel2= pd.DataFrame()
cedvel2["s_id"]=[102,103,105,106]
cedvel2["point"]=[77,96,100,83]

In [ ]:
cedvel1

   student_id  age
0         100   20
1         101   25
2         103   22
3         104   26
4         105   22

In [ ]:
cedvel2

   s_id  point
0   102     77
1   103     96
2   105    100
3   106     83

In [ ]:
cedvel3= cedvel1.merge(cedvel2, left_on="student_id", right_on="s_id", how="left")

In [ ]:
cedvel3

   student_id  age   s_id  point
0         100   20    NaN    NaN
1         101   25    NaN    NaN
2         103   22  103.0   96.0
3         104   26    NaN    NaN
4         105   22  105.0  100.0

In [ ]:
cedvel3= cedvel1.merge(cedvel2, left_on="student_id", right_on="s_id", how="right")

In [ ]:
cedvel3

   student_id   age  s_id  point
0         NaN   NaN   102     77
1       103.0  22.0   103     96
2       105.0  22.0   105    100
3         NaN   NaN   106     83

In [ ]:
cedvel3= cedvel1.merge(cedvel2, left_on="student_id", right_on="s_id", how="inner")

In [ ]:
cedvel3

   student_id  age  s_id  point
0         103   22   103     96
1         105   22   105    100

In [ ]:
cedvel2

   s_id  point
0   102     77
1   103     96
2   105    100
3   106     83

In [ ]:
cedvel2.rename(columns={"s_id":"student_id"}, inplace=True)

In [ ]:
cedvel2

   student_id  point
0         102     77
1         103     96
2         105    100
3         106     83

In [ ]:
cedvel1

   student_id  age
0         100   20
1         101   25
2         103   22
3         104   26
4         105   22

In [ ]:
cedvel3= cedvel1.merge(cedvel2, on="student_id", how="inner")

In [ ]:
cedvel3

   student_id  age  point
0         103   22     96
1         105   22    100

In [ ]:
cedvel1

   student_id  age
0         100   20
1         101   25
2         103   22
3         104   26
4         105   22

In [ ]:
cedvel2

   student_id  point
0         102     77
1         103     96
2         105    100
3         106     83

In [ ]:
cedvel1[cedvel1.age>22]

   student_id  age
1         101   25
3         104   26

In [ ]:
cedvel3= cedvel1[cedvel1.age>22].merge(cedvel2, on="student_id", how="left")

In [ ]:
cedvel3

   student_id  age  point
0         101   25    NaN
1         104   26    NaN

In [ ]:
#cedvel3= cedvel1.merge(cedvel2, on=["student_id","fin_code"], how="inner")

In [ ]:
cedvel1

   student_id  age
0         100   20
1         101   25
2         103   22
3         104   26
4         105   22

In [ ]:
cedvel2

   student_id  point
0         102     77
1         103     96
2         105    100
3         106     83

In [ ]:
cedvel1[cedvel1.student_id.isin(cedvel2.student_id)].iloc[:,:-1]

   student_id
2         103
4         105

In [ ]:
cedvel1[cedvel1.student_id.isin(cedvel2.student_id)].loc[:,["student_id"]]

   student_id
2         103
4         105

In [ ]:
cedvel1

   student_id  age
0         100   20
1         101   25
2         103   22
3         104   26
4         105   22

In [ ]:
yashlar=[22,25]
cedvel1[~cedvel1.age.isin(yashlar)]

   student_id  age
0         100   20
3         104   26

In [ ]:
cedvel1

   student_id  age
0         100   20
1         101   25
2         103   22
3         104   26
4         105   22

In [ ]:
cedvel1["age_shift"]=cedvel1.age.shift(2)

In [ ]:
cedvel1

   student_id  age  age_shift
0         100   20        NaN
1         101   25        NaN
2         103   22       20.0
3         104   26       25.0
4         105   22       22.0

In [ ]:
cedvel1["maash"]=[100, 140,180,190,250]

In [ ]:
cedvel1

   student_id  age  age_shift  maash
0         100   20        NaN    100
1         101   25        NaN    140
2         103   22       20.0    180
3         104   26       25.0    190
4         105   22       22.0    250

In [ ]:
cedvel1["maash_shift"]=cedvel1.maash.shift(1)

In [ ]:
cedvel1

   student_id  age  age_shift  maash  maash_shift
0         100   20        NaN    100          NaN
1         101   25        NaN    140        100.0
2         103   22       20.0    180        140.0
3         104   26       25.0    190        180.0
4         105   22       22.0    250        190.0

In [ ]:
cedvel1["muqayise"]=(cedvel1.maash-cedvel1.maash_shift)/cedvel1.maash_shift

In [ ]:
cedvel1

   student_id  age  age_shift  maash  maash_shift  muqayise
0         100   20        NaN    100          NaN       NaN
1         101   25        NaN    140        100.0  0.400000
2         103   22       20.0    180        140.0  0.285714
3         104   26       25.0    190        180.0  0.055556
4         105   22       22.0    250        190.0  0.315789

In [ ]:
import numpy as np

In [ ]:
cedvel1["artim30"]=np.where(cedvel1.muqayise>=0.3,1,0)

In [ ]:
cedvel1

   student_id  age  age_shift  maash  maash_shift  muqayise  artim30
0         100   20        NaN    100          NaN       NaN        0
1         101   25        NaN    140        100.0  0.400000        1
2         103   22       20.0    180        140.0  0.285714        0
3         104   26       25.0    190        180.0  0.055556        0
4         105   22       22.0    250        190.0  0.315789        1

In [ ]:
def age_yoxla(age):
    if age>22:
        return "yes"
    else:
        return "no"

In [ ]:
age_yoxla(26)

'yes'

In [ ]:
cedvel1

   student_id  age  age_shift  maash  maash_shift  muqayise  artim30
0         100   20        NaN    100          NaN       NaN        0
1         101   25        NaN    140        100.0  0.400000        1
2         103   22       20.0    180        140.0  0.285714        0
3         104   26       25.0    190        180.0  0.055556        0
4         105   22       22.0    250        190.0  0.315789        1

In [ ]:
cedvel1["age_name"]=cedvel1.age.apply(age_yoxla)

In [ ]:
cedvel1

   student_id  age  age_shift  maash  maash_shift  muqayise  artim30 age_name
0         100   20        NaN    100          NaN       NaN        0       no
1         101   25        NaN    140        100.0  0.400000        1      yes
2         103   22       20.0    180        140.0  0.285714        0       no
3         104   26       25.0    190        180.0  0.055556        0      yes
4         105   22       22.0    250        190.0  0.315789        1       no

In [ ]:
def maash_yoxla(maash,maash_shift):
    if ((maash-maash_shift)/maash_shift)>0.3:
        return 1
    else:
        return 0

In [ ]:
maash_yoxla(140,100)

1

In [ ]:
cedvel1["artim30_yeni"]=[maash_yoxla(i,t) for i,t in zip(cedvel1.maash, cedvel1.maash_shift) ]

In [ ]:
cedvel1

,student_id,age,age_shift,maash,maash_shift,muqayise,artim30,age_name,artim30_yeni
0,100,20,NaN,100,NaN,NaN,0,no,0
1,101,25,NaN,140,100.0,0.400000,1,yes,1
2,103,22,20.0,180,140.0,0.285714,0,no,0
3,104,26,25.0,190,180.0,0.055556,0,yes,0
4,105,22,22.0,250,190.0,0.315789,1,no,1

In [ ]:
list1=[]
for i in range(1,11):
    list1.append(i)

In [ ]:
list1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
list1=[i for i in range(1,11)]

In [ ]:
list1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
for i,t,z in zip(range(1,11), range(101,111),range(1001,1011)):
    print(i,t,z)

1 101 1001
2 102 1002
3 103 1003
4 104 1004
5 105 1005
6 106 1006
7 107 1007
8 108 1008
9 109 1009
10 110 1010